### ISSUE TITLE
`disableCookies` uses wrong quotes

### ISSUE THREAD

**Issue by MarcelWaldvogel** [jonashellmann/include-matomo#1]
When "disable cookies" is selected, Matomo is effectively disabled due to a syntax error.

`include-matomo.php` contains the following piece of code:

```php
  if (get_option('matomo_disable_cookies', 'n') == 'y') {
    echo "    _paq.push([‘disableCookies’]);\n";
  }
```

To fix this, the quotes around `disableCookies` should be changed to:
```php
  if (get_option('matomo_disable_cookies', 'n') == 'y') {
    echo "    _paq.push(['disableCookies’');\n";
  }
```

(If the code in this repository would match the plugin code, I would have opened a PR as well…)

**Comment by jonashellmann** [comment]
Hey, thank you very much for opening this issue! I just published version 1.5.1 of the plugin and the error should be fixed now.
Regarding the mismatch between the actual plugin code and the code in this repo: I forgot to push my local commits..
